### ISSUE TITLE
Improve wording/kinetic readme

### ISSUE THREAD

**Issue by GA-CyberWorkforceAcademy** [gacybercenter/kinetic-docs#1]
<Learn how to fork the kinetic framework and build your own cyber range on your own hardware, in order to address any potential IP or security concerns when using the hardware of a third party>  

Where am I learning this?  Kinetic needs more information in the Readme that is directly linked to this wording?   Are we supporting questions or assistance on this with current staffing positions?

**Comment by gacyberrange** [comment]
transferred upstream: https://gitlab.com/gacybercenter/gacyberrange/infrastructure/kinetic-docs/-/issues
