### ISSUE TITLE
Separate "Contributing" and "Getting Help"

### ISSUE THREAD

**Issue by GA-CyberWorkforceAcademy** [gacybercenter/kinetic-docs#3]
Separate Contributions from getting help. Add Help section to address issues as appropriate:

<If you’re looking to make a contribution or have a problem you need help with, you can go ahead and skip to the contributing section.>

**Comment by gacyberrange** [comment]
transferred upstream: https://gitlab.com/gacybercenter/gacyberrange/infrastructure/kinetic-docs/-/issues
