### ISSUE TITLE
Remove OR Specify pricing; remove reference to free time

### ISSUE THREAD

**Issue by GA-CyberWorkforceAcademy** [gacybercenter/kinetic-docs#5]
Build Pricing model for resources OR remove reference and add link to pricing model once established.  Remove mentions of free range time.

<Pricing information is still to be determined, but low/no cost compute/storage/bandwidth is available to noteworthy efforts that further the cause of cybersecurity for the world at large. For more information about this opportunity, please contact {{ fixme }}.>

**Comment by gacyberrange** [comment]
transferred upstream: https://gitlab.com/gacybercenter/gacyberrange/infrastructure/kinetic-docs/-/issues
