### ISSUE TITLE
specify capabilities

### ISSUE THREAD

**Issue by GA-CyberWorkforceAcademy** [gacybercenter/kinetic-docs#6]
Specify current capabilities, and contrast to future/potential capabilities.

<The limitations with these providers are the same as running it on your own laptop - they cannot capture the technical world beyond traditional x86 computing devices, which is a critical requirement in our current era of technology.>

**Comment by gacyberrange** [comment]
transferred upstream: https://gitlab.com/gacybercenter/gacyberrange/infrastructure/kinetic-docs/-/issues
