### ISSUE TITLE
Getting Started Needs

### ISSUE THREAD

**Issue by GA-CyberWorkforceAcademy** [gacybercenter/kinetic-docs#8]
•	Walk though creating a single instance from scratch via Horizon GUI.  
•	Walk through using a pre-configured/provided template to deploy a stack via Horizon/heat.
•	Questions/Errors/Issues/Help- guide to common user problems and how to resolve.

**Comment by gacyberrange** [comment]
transferred upstream: https://gitlab.com/gacybercenter/gacyberrange/infrastructure/kinetic-docs/-/issues
