### ISSUE TITLE
Staff technical documentation needs

### ISSUE THREAD

**Issue by GA-CyberWorkforceAcademy** [gacybercenter/kinetic-docs#9]
•	Resource allocation instructions
•	Instructions for tracking consumption for sales/billing.
•	More specific examples for process for pulling technical details (IPs, names etc.)
•	Physical diagrams ( wiring diagram, power diagram)
•	Improve instructions for how(and why) to increase (or decrease) level of parallelism and change order in which things are accomplished.

**Comment by gacyberrange** [comment]
transferred upstream: https://gitlab.com/gacybercenter/gacyberrange/infrastructure/kinetic-docs/-/issues
